name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: AssetStudio.sln
  PROJECT_FILE_PATH: AssetStudioGUI/AssetStudioGUI.csproj
  BUILD_CONFIGURATION: Release
  TARGET_FRAMEWORK: net6.0-windows

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore ${{ env.SOLUTION_FILE_PATH }}

    - name: Build project
      run: msbuild ${{ env.PROJECT_FILE_PATH }} /m /p:Configuration=${{ env.BUILD_CONFIGURATION }} /p:TargetFramework=${{ env.TARGET_FRAMEWORK }} /verbosity:minimal

    - name: Upload build output
      uses: actions/upload-artifact@v4
      with:
        name: AssetStudioGUI-${{ env.TARGET_FRAMEWORK }}
        path: AssetStudioGUI/bin/${{ env.BUILD_CONFIGURATION }}/${{ env.TARGET_FRAMEWORK }}/